### ISSUE TITLE
feature request: option to let apps which support it use replies

### ISSUE THREAD

**Issue by tabascoeye** [BennoGAP/notification-forwarder-v3#1]
I found there is an app which has the same use-case but has working replies.
The huge con for that is that the apps it supports is hardcoded and limited to just a few (WhatsApp, Telegram,...).
(https://play.google.com/store/apps/details?id=com.integrationsfortesla.messaging&hl=en&gl=US)

From what I understand/suspect, the app does the following different from notification-forwarder-v3:
* it listens to incoming SMS/MMS from the car via bluetooth MAP/OBEX (probably via an intent?)
* It "maps" the incoming SMS to the matching app and sender in that app
* It parses the text from those and puts them into the "quick reply" of the notification it was a reply to
* it manages to NOT actually send an SMS (prunes the outbox I guess?)

For the "use the notification to direct-reply" thing there are a few links:
https://mobikul.com/direct-reply-from-notification/
https://medium.com/software-engineers-toolbox/direct-reply-notification-for-android-in-4-steps-5612b49b5487
https://stackoverflow.com/questions/59251922/how-to-send-a-reply-from-a-notification

But for the "listen to incoming SMS and react on them" it's hard to find something solid.
I have seen the "outbox":
http://docs.52im.net/extend/docs/api/android-50/reference/android/provider/Telephony.Sms.Outbox.html

So it would be **amazing** if we could:
* check if an app supports the "reply in-line in notification" functionality
* make it so that answers from the car are re-routed to that reply function
* maybe have a config option to enable/disable that

**Comment by BennoGAP** [comment]
Hi,
thanks for your suggestion.

From my understanding the app does the following:
- Create a temporary contact for each User/App-combination (John send me a WhatsApp-Msg -> Create a contact "John - WhatApp" with the number 316)
- When the message is answered, the car send an reply to the number 316 (because for the car, thats the contact-number for this message) - the app sees that msg in the outbox, get the informations from that message, remembering that 316 means "John" from "WhatsApp" and delete the message from the outbox
- As the number 316 (and the following numbers) are not real phone-numbers, there wont be a sms to the specific contact
- BUT (from my understanding) the sms message is still send out to the phone provider - the phone provider answer with "sending failed" because he doesnt know a phonenumber "316". This is working on the technial side - but i dont like the idea, that the message is send to the phone provider anyway.

While this itself is managable to implement, there are a few problems:
- This seems to work fine on a Tesla - however a lot of cars fetch the phonebook at the beginning of the Bluetooth connection - so the "create a temporary contact to show 'John - WhatsApp'" does not work here.
- And (maybe the bigger problem) - I dont have a car where i can use the reply, so i cant even test if it is working

I will consider this as an additonal option in the future - but not with a very high priority

**Comment by johan12345** [comment]
Hi, I would also be interested in this feature and could help with testing or possibly even try to contribute.

> BUT (from my understanding) the sms message is still send out to the phone provider - the phone provider answer with "sending failed" because he doesnt know a phonenumber "316". This is working on the technial side - but i dont like the idea, that the message is send to the phone provider anyway.

Hm yeah, simply taking "316" and assuming this number will fail might not be ideal. Maybe we should instead try a very long number (> 15 digits should be [pretty unlikely](https://en.wikipedia.org/wiki/E.164#Numbering_formats) to be a valid number...)? Though I guess that might still be sent to the provider instead of failing locally, right?

> This seems to work fine on a Tesla - however a lot of cars fetch the phonebook at the beginning of the Bluetooth connection - so the "create a temporary contact to show 'John - WhatsApp'" does not work here.

In this case the reply function would still work, the name of the contact would just not be shown in the car - right? So yeah, this should definitely be an optional feature with a thorough description how it works and why it might break the display of contact names in some cars.

**Comment by Setoku** [comment]
Would be great to have the reply feature added 
This app works nicely in tesla

**Comment by DevNull-00** [comment]
+1
I also would find this feature very useful.
As of now, I use this app in the car to read the message and the google assistant to reply, so not ideal
